### ISSUE TITLE
Example using container.yaml

### ISSUE THREAD

**Issue by andruschka** [gardenhq/o#1]
Sorry guys - I just don't get it how to use with yaml file?

**Comment by gardener-gardenhq** [comment]
Hi, 

Have a look in here:

https://github.com/gardenhq/o/tree/master/examples/b/yaml

..which you'll see running here:

https://greenhouse.gardenhq.io/o/examples/b/yaml/index.html

I'm guessing you had a look in the 'examples' folder in the repo, but only got one level in, so we'll shift the 'yaml' folder up so people are more likely to see it, and probably add a link in the README also.

Let us know how it goes. Oh and sorry for the delay in coming back, only saw this this morning.

**Comment by andruschka** [comment]
wow ok this works! nice job.
Actually like that i dont have to npm install and setup all the stuff.
But when using the yaml file I get a lot of unpg not resolved errors before the function actually gets executed...

**Comment by gardener-gardenhq** [comment]
Yeah, no node, no npm is a big bonus in our eyes. Node is great and all, except when its not :)

So where are you getting these errors here:

https://greenhouse.gardenhq.io/o/examples/b/yaml/index.html

?

**Comment by gardener-gardenhq** [comment]
Oh and also, if you are requiring stuff the node way - i.e not giving entire paths to stuff so:

```
"react"
```

You will get resolving errors until o finds the file. This will only happen on first load, the toolbar will cache where it eventually finds it (in this case 'react/react.js') so you will only get the errors on first load (and every time you entirely clear the cache), they are caught so they shouldn't effect what you are building.

'Think internet' here, specify entire paths if you don't want the errors so

```
"react/dist/react.min.js"
```

The internet doesn't automatically look up file paths so nor should javascript.

**Comment by andruschka** [comment]
ok got it 👍

**Comment by gardener-gardenhq** [comment]
Good stuff, give us a yell if there's anything else.

Just incase anyone else reads through this. You don't HAVE to specify full paths, you can still use 'module-names' like in node. o will do a 'node-like' lookup over http, so you can get big red 404 'warnings' in `console` as it walks over possible files.

So, if you require "module" it will walk through module.js, module/index.js, module/index.json, module/package.json. If it gets to package.json it will grab the main value and use that for its final attempt. Basically the 'node resolve dance'.

Important thing to note is that if you are in development (using o.dev.js), and using the reloader, **this will only happen the very first time you load your page**. Once o knows what you are looking for, it caches it so it doesn't need to do the dance again. Once you are bundled, it it won't do this at all of course.

We try to be specific, so we try to specify the exact path. If you like the node dance, or you are using modules that do (pretty much a given) then thats fine we've got you covered.
