### ISSUE TITLE
Name project is very bad

### ISSUE THREAD

**Issue by docentq2** [gardenhq/o#2]
If I want to google `o` I'll get nothing - [example](https://www.google.com/?q=o&gws_rd=cr&ei=CNNAWaC9MObJ6ATRkJXICw#newwindow=1&q=o).

If I search `o` in any project I'll get the same!

Please, rename your project.

**Comment by gardener-gardenhq** [comment]
It's called `gardenhq/o`, that long enough for you? ;)

https://www.google.co.uk/search?q=gardenhq%2Fo

First result.

We namespace everything, even if the name is not taken on npm

> If I search o in any project I'll get the same!

Not quite sure what you mean by this, but we let you control what it's called/exported as in a browser via `data-export`

https://greenhouse.gardenhq.io/o/docs/reference/html-attributes.html#data-export

Call it `supercalifragalisticexpialidocious` if you like :)

```
<script type="text/javascript"
    src="/node_modules/@gardenhq/o/o.js" <!-- or source it from unpkg -->
    data-export="supercalifragalisticexpialidocious" 
    data-src="index.js"
></script>
```
```javascript
// index.js
(
    function(yippee)
    {
        ...
    }
)(supercalifragalisticexpialidocious(function(Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch){ return Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch(document)}));
```

`o` is easier to type though :)

Also, you should only be using the letter `o` (if at all) once in your 'bootstrapping' code anyhow.

If you are in node, doing backend work, you are probably using `@gardenhq/willow` via `@gardenhq/o`:

https://greenhouse.gardenhq.io/o/docs/node-usage/index.html

In which case again you can require it and call it whatever you like:

```javascript
(
    function(load)
    {
        load.then(
            function(builder)
            {
                return builder.build(__dirname + "/container.yaml").run("main");
                // don't want yaml?
                // return builder.build(__dirname + "/container.js").run("main");
            }
        ).catch(
            function(e)
            {
                console.error(e);
            }
        );
    }
)(require("@gardenhq/o/builder.js")(function(huzzah){return huzzah(require)}));

```

There are reasons its 'called' `o`, happy to reconsider if you can give me a better reason :)

Let me know if that addresses your issue.
